### ISSUE TITLE
Hash user ID only when set?

### ISSUE THREAD

**Issue by mattab** [iMarkus/Piwik-HashUserId#1]
Hi @iMarkus 
Congrats on launching the plugin on the marketplace!

We took a quick look and wondering if in https://github.com/iMarkus/Piwik-HashUserId/blob/master/Columns/UserId.php you should only hash the value when it is originally set? otherwise it looks like all visits without a user ID will get all the same user ID and this would likely make the reports and visits wrong?

Thanks,

**Comment by iMarkus** [comment]
Hi @mattab ,
thanks for that hint. You are totally right! Therefore a simple isset should be sufficient i guess.

```php
$uid = $visitor->getVisitorColumn('user_id');
if(isset($uid))
{
  $salt = Config::getInstance()->General['salt'];
  $hash = substr(sha1($salt.$uid), 0, 16);
  $visitor->setVisitorColumn('user_id', $hash);
  return $hash;
}
return $uid;
```
What do you think?

**Comment by mattab** [comment]
Probably safer to use !empty() in case the $uid is empty or so, isset would still return true.

**Comment by iMarkus** [comment]
Hi @mattab,
thanks.

Plugin updated.

cheers
